### ISSUE TITLE
chaskey is not available

### ISSUE THREAD

**Issue by CaledoniaProject** [volexity/donut-decryptor#2]
Is that a typo?

**Comment by tlansec** [comment]
It's unclear exactly what you mean. This library has a dependency on another library: https://github.com/volexity/chaskey-lts - which must be installed prior to the installation of this library.

**Comment by CaledoniaProject** [comment]
I figured out. https://github.com/volexity/chaskey-lts is not published on pypi, and setup.py won't work due to that. Can you fix it?

**Comment by CaledoniaProject** [comment]
You also forget to add yara to your dependency list

**Comment by tlansec** [comment]
The `README.md` states that the `chaskey-lts` module must be installed separately. We do not currently have plans to publish either this library or `chaskey-lts` on pypi

I'll add yara to the list of dependencies, this was an oversight.

**Comment by CaledoniaProject** [comment]
I have a problem with the yara rules, `data/rules.yar:14: syntax error, unexpected _IDENTIFIER_, expecting _CONDITION_`

```
 $base64 = "\x48\x89\x5c\x24\x08\x48\x89\x6c\x24\x10\x48\x89\x74\x24\x18\x57\x41\x56\x41\x57\x48\x81\xec\x00\x05\x00\x00\x33\xff\x48\x8b\xd9\x39\xb9\x38\x02\x00\x00\x0f\x84\xce\x00\x00\x00\x4c\x8b\x41\x28" base64
```

I have yara-1.7.7 with python 3.11 on MacOS

**Comment by tlansec** [comment]
The modifier `base64` used in the rules was added in YARA 4.0.0 (I think). You'll need YARA >= 4.0.0.

I'll update the setup.cfg file to reflect the requirement for a version >4.0.0.
